cmd/src-fingerprint/main.go

Minor change to correctly display the version when running `src-fingerprint --help`.
With the last release the output is:
```
NAME:
src-fingerprint - Collect user/organization file hashes from your vcs provider of choice
USAGE:
src-fingerprint [global options] command [command options] [arguments...]
VERSION:
unknown
[...]
```
With this diff the output becomes:
```
NAME:
src-fingerprint - Collect user/organization file hashes from your vcs provider of choice
USAGE:
src-fingerprint [global options] command [command options] [arguments...]
VERSION:
dev
[...]
```

fix(cmd): Correctly display version in --help

---

.github/workflows/tag.yml
.goreleaser.yml

In this MR, we add a goreleaser CI step to create a brew formula and push it to GitGuardian's tap.  
This behavior was tested [here](https://github.com/pierrelalanne/my-src-fingerprint/actions/runs/1502878053).   
My only concern is whether the `GITHUB_TOKEN` associated by default to the repo will have enough rights to push to `GitGuardian/homebrew-tap`, from what I read, it should be ok. Otherwise we'd have to push a fix to use another token, and add the token to the repo secrets.

Add a CI step with goreleaser to push a brew formula to gitguardian's tap

---

.github/workflows/tag.yml

In this PR, we intend to fix an error we had when running the goreleaser CI step.  
See this [error logs](https://github.com/GitGuardian/src-fingerprint/runs/4410401195?check_suite_focus=true).

chore(ci): fix broken goreleaser CI

---

cmd/src-fingerprint/main.go

closes https://github.com/GitGuardian/src-fingerprint/issues/15
Only print the advancement of the analysis after the 1st file is analyzed and improve the output of the final stats.

fix(log): Improve INFO logs during analysis

---

.github/workflows/test.yml
.golangci.yml
cmd/src-fingerprint/main.go
exporter/output.go

closes #13 
In this PR:
- two new output formats are implemented: `gzip-jsonl` and `gzip-json` (`gzip-jsonl` becomes the new default format)
- when the output is a file, its path is printed to the stout at the end
- better handle (unlikely) errors when closing the output file

Improve output generation

---

.golangci.yml
cmd/src-fingerprint/main.go
extractor.go
pipeline.go
pipeline_test.go

closes #14 
This PR adds an argument `limit` to limit the number of repositories analyzed. When the limit is reached, a warning appears with the number of ignored repositories. The default value of limit is 100 and 0 means no-limit.
Here's an example without verbose:
```
▶ go run cmd/src-fingerprint/main.go -p github -u GitGuardian -o /tmp/sha.jsonl --limit 2 
WARN[0000] Limit reached of repositories! 7 repositories ignored 
Collected file hashes saved in file /tmp/sha.jsonl
```
And with verbose:
```
▶ go run cmd/src-fingerprint/main.go -p github -u GitGuardian  -o /tmp/sha.jsonl --limit 2 -v
INFO[0000] Extracting user GitGuardian                  
INFO[0000] Gathering page 1/? for GitGuardian           
WARN[0000] Limit reached of repositories! 7 repositories ignored 
INFO[0000] Done …
```

feat(cli): Add argument to limit the number of repositories analyzed

---

cmd/src-fingerprint/main.go
pipeline.go
provider/gitlab.go

In this MR, we fixed the GitLab flow for `src-fingerprint`.  
Before this fix : the lookup of all accessible repos to a user would have returned all repos accessible including all available public repos, this resulted in a long list of repos to fetch. Also the group lookup was broken because the value to lookup was the group "id" and not the group name.  
To fix this, we :
- Added a [membership option](https://docs.gitlab.com/ee/api/projects.html#list-all-projects) to restrict the list of projects/
- Changed a condition when looking up group to use both the group name or its "path" (see these available [attributes](https://pkg.go.dev/github.com/xanzy/go-gitlab#Group)). This is to handle both behaviors for GitLab enterprise and public.
Also, for clarity :
- We renamed "user" to object, as …

feat(provider): fix gitlab flow

---

cmd/src-fingerprint/main.go
provider/generic_repository.go
provider/provider.go

When using the provider 'repository' we add options to precise a
repo-name and whether the repo is private or not in the final outputs.  
This is in order to avoid `jsonl` outputs where the repository_name is not filled, and the private field is inconsistent.

feat(provider): add information when using the provider repository

---

cmd/src-fingerprint/main.go
provider/github.go
provider/provider.go

closes #23 
This PR only changes the behavior of the GitHub provider. By default, it will only gather hashes from private repositories and the added flag `--all` can be used to gather hashes from every repository.
I've also included a fix for the GitHub provider. If there is more than 100 repositories, `src-fingerprint` will only query the first 100 repos and duplicate them. (Always querying the first page of 100 repositories)

feat(github): By default, only gather hashes from private repositories

---

.goreleaser.yml

In this MR, we leverage `nfpm` option of goreleaser to support rpm and deb packaging. Read this [documentation](https://goreleaser.com/customization/nfpm/) for some more details.  
**Note :** We also get rid of support for 32 bit architectures which did not make much sense.
Here are the archives we will finally have in a release :  
```shell
src-fingerprint_0.12.0_Darwin_amd64.tar.gz
src-fingerprint_0.12.0_Darwin_arm64.tar.gz
src-fingerprint_0.12.0_Linux_amd64.deb
src-fingerprint_0.12.0_Linux_amd64.rpm
src-fingerprint_0.12.0_Linux_amd64.tar.gz
src-fingerprint_0.12.0_Linux_arm64.deb
src-fingerprint_0.12.0_Linux_arm64.rpm
src-fingerprint_0.12.0_Linux_arm64.tar.gz
src-fingerprint_0.12.0_Windows_amd64.tar.gz
src-fingerprint_0.12.0_Windows_arm64.tar.gz
``` 
Note that although the …

feat(goreleaser): generate rpm and deb during releases

---

.goreleaser.yml
CONTRIBUTING.md
Makefile

This PR improves a few details of the generated archives and Linux packages:
- archives are now in their own directory
- Windows archives are zip files
- deb and rpm contains more metadata and include the README.md and LICENSE files
I also added a `dist` Makefile target to make it easier to work on packaging.

Improve packaging

---

.github/workflows/tag.yml
.goreleaser.yml
README.md
scripts/goreleaser-cloudsmith-publisher

This PR makes goreleaser publish the deb and rpm packages it produces on [Cloudsmith](https://cloudsmith.com/).
The test packages are available here: https://cloudsmith.io/~gitguardian/repos/src-fingerprint/packages/
The release script was tested by running `goreleaser release --skip-validate --skip-announce --rm-dist` from a Docker, with a fake GitHub token. It uploaded the packages which are currently on Cloudsmith.
I tested the install process provided by Cloudsmith on Docker images (debian:stable and centos:latest) for amd64 binaries and in a Debian QEMU VM for arm64 binaries.
This PR is a draft because it should not be merged until a `CLOUDSMITH_API_KEY` environment variable has been added to the repository configuration.

chore(ci): publish deb and rpm packages on Cloudsmith

---

cloner/cloner.go
extractor.go

In this MR, we fix the following bug :  
When collecting fingerprints for a set of repositories, some repositories were kept in the `--clone-dir` folder whereas they should have been deleted at the end of the process.  
To fix this :  
- First we added a log to clearly log when folders are deleted.
- We delayed the closing of the `gitFiles` channel in the `extractor`. Indeed, my suspicion is that closing this channel when manipulating the last repo analyzed causes the program execution to stop because the `eventChannel` becomes empty and can't be consumed anymore. Hence if we close the `gitFiles` early, the the last repo cloned was not removed in the end.

Fix deletion of cloned repos

---

extractor.go

In this PR, we handle behavior of the program if a line of the git command cannot be unmarshaled.  
To reproduce, you can try this command :  
```shell
env VCS_TOKEN=<TOKEN_HERE> ./src-fingerprint -v --provider repository --object "https://github.com/Linkedin/gobblin-elr"
```  
This repo will produce an error on one given fingerprint.  
- Before this PR : this ends up producing an "incorrect" line in the jsonl output. With empty type, size and sha.
- After this PR : the concerned fingerprint is ignored and is not part of the output anymore.
If you have ideas regarding why the error happens in the first place, this can be interesting, I did not find any obvious reason for this.

fix(extractor): ignore lines that generate unmarshaling errors

---

README.md
scripts/windows-installer.ps1

This PR adds a PowerShell script to install src-fingerprint on Windows.
It also refreshes a bit the install part of the README.
Some notes:
- The script installs in `C:\Users\<user>\AppData\Roaming\src-fingerprint` by default, because this directory does not require special user rights. Other apps, Chrome for example, do the same when running on unprivileged accounts.
- The link in the README won't work until the PR is merged, since it assumes downloading from the `main` branch. Replace `main` with `agateau/pdd-34/windows-install` to test.

Add Windows install PowerShell script

---

.github/workflows/test.yml
.gitlab-ci.yml
cmd/src-fingerprint/main.go
tests/integration_test.py

In this MR, we do the following :  
1. Remove useless .gitlab-ci.yml file
2. Change wording from `file hashes` to `fingerprints`
3. Introduce python tests to test src-fingerprint end to end in the CI, here are some details hereunder.
- We created a user `gg-src-fingerprint` that has a bunch of repos : public, private, public archived, private archived and forked ones.
- We created an org [`gg-src-fingerprint-org`](https://github.com/gg-src-fingerprint-org) on which the user [`gg-src-fingerprint`](https://github.com/gg-src-fingerprint) created a bunch of repos in the same fashion with different types. Another user also created a private repo on the org, to test the case where `src-fingerprint` gathers all fingerprints of an org.
- The CI test runs on each push, and uses …

Add integration tests

---

provider/generic_repository.go
tests/integration_test.py

With the `repository` provider, if the name of the repository is omitted, it will be infer from the URL/path. 
Now, `src-fingerprint --provider repository --object "https://github.com/GitGuardian/src-fingerprint"` will produce:
```json
{
"repository_name": "src-fingerprint",
"private": false,
"sha": "a0c16efce5e767f04ba0c6988d121147099a17df",
"type": "blob",
"filepath": ".env.example",
"size": "31"
}
...
```
closes https://github.com/GitGuardian/src-fingerprint/issues/26

feat(provider): Repository provider infers the repo name when omitted

---

cmd/src-fingerprint/main.go
provider/generic_repository.go

Following #44 
- Improve the inference of the repository name by the repository provider by using the absolute path when the target is a path.
- Add a flag to see the debug-logging logs
- It would have helped with #40 because the logs are:
```
time="2022-02-08T17:26:13+01:00" level=debug msg="parsing line {\"sha\": \"67ffd75100bd8d4dd237734e6618530cef13dfee\", \"type\": \"blob\", \"filepath\": \
"gobblin-core/src/main/java/gobblin/converter/avro/test\x10.schema\", \"size\": \"5388\"}"
time="2022-02-08T17:26:13+01:00" level=warning msg="Error while parsing {\"sha\": \"67ffd75100bd8d4dd237734e6618530cef13dfee\", \"type\": \"blob\", \"filepath\": \"gobblin-core/src/main/java/gobblin/converter/avro/test\x10.schema\", \"size\": \"5388\"} invalid character '\\x10' in string literal"
```
We can …

Improve the inference of the repository name by the repository provider

---

CONTRIBUTING.md
README.md
cmd/src-fingerprint/main.go
provider/generic_repository.go
tests/integration_test.py

In this PR, we re-organize the CLI to allow subcommands, this is in order to be prepared for any future development if the util is meant to do more than collecting fingerprints.  
What we have done :  
- Add a subcommand in the CLI
- Modify README accordingly
- Modify comment mentioning commands
- Modify tests to use this command

Add subcommand to the CLI

---

provider/generic_repository.go

Fix inference of the name of the repository on Windows.

fix(provider): Use 'os.PathSeparator' to correctly split path on Windows

---

README.md

In this PR we update the Readme to give some extra detail on the `provider-url` option and fix the required scope for GitLab tokens.
close #53

chore(readme): update readme for the project

---

.github/workflows/test.yml
cmd/src-fingerprint/main.go
extractor.go
provider/bitbucket.go
tests/integration_test.py

In this PR :  
- we add integration tests for BitBucket
- we clean some logging
Secrets were added to the repo as well.
A successful run of the CI pipeline can be found [here](https://github.com/pierrelalanne/src-fingerprint/runs/5364545846).

Add integration tests bitbucket

---

tests/integration_test.py

We can have empty repos in the integration tests.
We changed the test to check that the final number of repos is below the expected limit. We also added a check on the logs.
closes #56

fix(integration_tests): fix integration test on limit

---

.goreleaser.yml
README.md
cmd/src-fingerprint/main.go
cmd/src-fingerprint/run_extract.go
go.mod
go.sum
tests/integration_test.py

Using [tunny](github.com/Jeffail/tunny), this PR makes `src-fingerprint` execute the extraction of multiple objects in a pool of goroutines. This size of the pool is controlled by the new argument `--pool`, by default the behavior of `src-fingerprint` stays the same and the size of the pool is 1.
I've also included a small fix for unix builds, by adding `procps` as a dependency for the deb/rpm release.

Run the extraction of multiple objects in a pool of goroutines
